"""Forge outer loop.

Per-harness flow (`status=search` or `test`):

    propose → ensure_image
           → sanity_check_harness (small real-data run per dataset, if
                                   sanity.enabled)
               ├─ pass    → evaluate_harness (full run per dataset) → frontier
               └─ fail    → propose_with_fix(error_trace) → retry (max K times)
                             ├─ eventually pass → evaluate_harness
                             └─ all retries exhausted → skip eval,
                                 enter frontier with sanity_failed + score=0

For `status=devtest`: skip sanity entirely and run evaluator with
`check_n_*` sizes (devtest IS the sanity-size dev verification).

Two ways to launch:

    # (a) config-first (recommended for long runs / reproducibility)
    python -m forge.orchestrator --config configs/search.yaml

    # (b) CLI-first (quick iteration; uniform params across all datasets)
    python -m forge.orchestrator --steps 3 --datasets dynamicmem,locomo \
        --status devtest --eval-n-samples 2 --eval-n-qa 10

CLI flags always override the config file when both are given. See
`configs/smoke.yaml` and `configs/search.yaml` for the full config schema.

Outputs (per-run, under workspace/<run_id>/):
    harnesses/<int>_<hash>/<dataset>/         full-eval score + traces + memory_dumps
    harnesses/<int>_<hash>/<dataset>/sanity/  small sanity-check score + traces
    harnesses/<int>_<hash>/harness.py         the harness code itself
    harnesses/<int>_<hash>/meta.json          parent_ids, description, content_hash, created_at
    frontier.json                             population snapshot (with sanity_status)
    forge/logs/orchestrator.log               rotating log (shared across runs)

Per-harness eval over multiple datasets is serial (one Singularity exec per
dataset). `Frontier.entries[i].objectives` stores both the mean ("accuracy")
and per-dataset scores ("accuracy_<dataset>"). v4: parent selection is
delegated to the proposer agent — the search loop has NO selection rule.
v5: each orchestrator invocation gets its own per-run dir (`--run-name`
or auto timestamp); harness dirs are renamed `<int>` → `<int>_<hash8>`
after sanity loop settles, before full eval.
"""
from __future__ import annotations

import argparse
import asyncio
import copy
import datetime as _dt
import hashlib
import json
import logging
import os
import shutil
import sys
import time
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml

from forge.env_builder import EnvBuildError, ensure_image
from forge.evaluator import run_evaluation
from forge.paths import (
    LOGS_DIR,
    SEEDS_DIR,
    ensure_dirs,
    paths,
)
from forge.proposer import propose, propose_with_fix
from forge.selection import Entry, Frontier

log = logging.getLogger("forge.orchestrator")


# ---------------------------------------------------------------------------
# Config resolution: defaults ← YAML file ← CLI overrides
# ---------------------------------------------------------------------------

DEFAULT_CONFIG: Dict[str, Any] = {
    "steps": 1,
    # search  — train/explore on search split, full eval size, sanity respected
    # test    — held-out test split, full eval size, sanity respected
    # devtest — quick dev verification: search split, check eval size, sanity always skipped
    "status": "search",
    "model": "gpt-5-mini",
    "judge_model": "gpt-5-mini",
    "update_type": "all_at_once",
    "max_sample_concurrent": 3,
    "memory_dumps": "full",   # full | stats | none — post-Phase-1 memo dump policy
    "proposer": {
        "model": "claude-opus-4-7",
        "max_turns": 80,
        "timeout_s": 25 * 60,
        # Tools blocked inside the proposer container. Default: only the MCP
        # wildcard (no MCP servers configured on this host, but if any are
        # added they shouldn't be reachable by the proposer without an
        # explicit opt-in). Pass [] to allow ALL tools, or extend with e.g.
        # ["Bash", "WebFetch"] for tighter sandboxes / ablation experiments.
        # Filesystem isolation is enforced by Singularity binds, not this list.
        "disallowed_tools": ["mcp__*"],
    },
    "selection": {
        # tau is still consumed by Frontier.sample_parent if the held-out test
        # script needs a stochastic top-K pick. NOT used by search_loop —
        # parent selection is fully delegated to the proposer agent (v4).
        "tau": 0.5,
    },
    "propose": {
        # k harnesses proposed per outer-loop step. Default 2 follows the
        # Meta-Harness paper. Each is generated by an independent CC-SDK call.
        "k_per_step": 2,
    },
    "sanity": {
        "enabled": True,      # run pre-eval sanity (mode=check small run) when top-level mode=eval
        "max_retries": 2,     # on sanity failure, call propose_with_fix up to this many times
    },
    "seed": {
        # When enabled, copy seeds/<source>/ → <run>/harnesses/0/ at startup
        # to give the proposer a known baseline to reference. Default is OFF
        # — CC writes the first harness from scratch with parent_ids=[].
        # Opt in via `seed: {enabled: true, source: <name>}` in YAML or the
        # `--seed` CLI flag.
        "enabled": False,
        "source": "no_memory",
    },
    "gpu": {
        # When enabled, evaluator runs `singularity exec --nv ...` so the
        # container can use the host's NVIDIA driver (libcuda.so) and any
        # GPUs visible at /dev/nvidia*. Default OFF for portability — turning
        # on couples runs to a host with a compatible NVIDIA driver. Opt in
        # via `gpu: {enabled: true}` in YAML or `--gpu` CLI flag.
        # Proposer container does NOT honor this (CC just makes API calls).
        "enabled": False,
    },
    # `run_name` defaults to a timestamp at resolve time (so the default isn't
    # frozen at import time). `datasets` intentionally omitted from defaults.
}


def _deep_merge(base: Dict[str, Any], overlay: Dict[str, Any]) -> None:
    """In-place deep merge of overlay into base (dicts only)."""
    for k, v in overlay.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            _deep_merge(base[k], v)
        else:
            base[k] = v


def _resolve_config(args: argparse.Namespace) -> Dict[str, Any]:
    """Build the effective run config from defaults, optional YAML, and CLI.

    Precedence (lowest → highest):
      1. DEFAULT_CONFIG (this module)
      2. YAML at --config path (if given)
      3. Explicit CLI args (only when not None)
    """
    cfg: Dict[str, Any] = copy.deepcopy(DEFAULT_CONFIG)

    if args.config is not None:
        path = Path(args.config)
        if not path.exists():
            raise FileNotFoundError(f"config file not found: {path}")
        with path.open("r", encoding="utf-8") as f:
            file_cfg = yaml.safe_load(f) or {}
        if not isinstance(file_cfg, dict):
            raise ValueError(f"config file must be a mapping at top level: {path}")
        _deep_merge(cfg, file_cfg)

    # Top-level CLI overrides (each applied only if explicitly provided)
    for key in (
        "steps", "status", "model", "judge_model",
        "update_type", "max_sample_concurrent", "memory_dumps",
    ):
        val = getattr(args, key, None)
        if val is not None:
            cfg[key] = val

    # Nested proposer / selection / sanity overrides
    _proposer_map = {
        "proposer_model": "model",
        "proposer_max_turns": "max_turns",
        "proposer_timeout_s": "timeout_s",
    }
    for cli_key, cfg_key in _proposer_map.items():
        val = getattr(args, cli_key, None)
        if val is not None:
            cfg["proposer"][cfg_key] = val
    # disallowed_tools: comma-separated. Empty string = allow everything.
    if args.proposer_disallowed_tools is not None:
        cfg["proposer"]["disallowed_tools"] = [
            t.strip() for t in args.proposer_disallowed_tools.split(",") if t.strip()
        ]
    if args.tau is not None:
        cfg["selection"]["tau"] = args.tau
    if args.k_per_step is not None:
        cfg["propose"]["k_per_step"] = args.k_per_step
    if args.no_sanity:
        cfg["sanity"]["enabled"] = False
    if args.sanity_max_retries is not None:
        cfg["sanity"]["max_retries"] = args.sanity_max_retries
    if args.no_seed:
        cfg["seed"]["enabled"] = False
    if args.seed_source is not None:
        cfg["seed"]["source"] = args.seed_source
    if args.gpu:
        cfg["gpu"]["enabled"] = True

    # run_name: CLI > YAML > timestamp default. Resolved here (not in
    # DEFAULT_CONFIG) so `from forge.orchestrator import DEFAULT_CONFIG`
    # doesn't freeze the timestamp at import time.
    if args.run_name is not None:
        cfg["run_name"] = args.run_name
    cfg.setdefault("run_name", _dt.datetime.now().strftime("%Y%m%d_%H%M%S"))

    # Datasets
    cli_datasets = getattr(args, "datasets", None)
    if cli_datasets is not None:
        # CLI --datasets replaces the YAML datasets block entirely. Uses the
        # global --eval-n-samples / --eval-n-qa / --check-n-samples / --check-n-qa
        # (or their defaults) for every benchmark in the list.
        ds_list = [d.strip() for d in cli_datasets.split(",") if d.strip()]
        eval_ns = args.eval_n_samples if args.eval_n_samples is not None else 1
        eval_nq = args.eval_n_qa  # None is fine; longmemeval ignores it
        check_ns = args.check_n_samples if args.check_n_samples is not None else 1
        check_nq = args.check_n_qa if args.check_n_qa is not None else 3
        cfg["datasets"] = {
            ds: {
                "eval_n_samples": eval_ns, "eval_n_qa": eval_nq,
                "check_n_samples": check_ns, "check_n_qa": check_nq,
            }
            for ds in ds_list
        }
    else:
        # Global CLI args override every dataset in the YAML
        if args.eval_n_samples is not None and cfg.get("datasets"):
            for ds in cfg["datasets"]:
                cfg["datasets"][ds]["eval_n_samples"] = args.eval_n_samples
        if args.eval_n_qa is not None and cfg.get("datasets"):
            for ds in cfg["datasets"]:
                cfg["datasets"][ds]["eval_n_qa"] = args.eval_n_qa
        if args.check_n_samples is not None and cfg.get("datasets"):
            for ds in cfg["datasets"]:
                cfg["datasets"][ds]["check_n_samples"] = args.check_n_samples
        if args.check_n_qa is not None and cfg.get("datasets"):
            for ds in cfg["datasets"]:
                cfg["datasets"][ds]["check_n_qa"] = args.check_n_qa

    # Validation
    if not cfg.get("datasets"):
        raise ValueError(
            "No datasets specified. Provide `datasets:` in --config YAML, "
            "or pass --datasets on the CLI."
        )
    for ds, params in cfg["datasets"].items():
        if not isinstance(params, dict):
            raise ValueError(
                f"datasets.{ds} must be a mapping, got {type(params).__name__}"
            )
        params.setdefault("eval_n_samples", 1)
        params.setdefault("eval_n_qa", None)
        params.setdefault("check_n_samples", 1)
        params.setdefault("check_n_qa", 3)

    return cfg


# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

_LOG_FORMATTER = logging.Formatter(
    "%(asctime)s %(name)s [%(levelname)s] %(message)s"
)


def _setup_logging(verbose: bool) -> None:
    """Phase-1 logging: console + global rotating tape (run-agnostic).

    The per-run file handler is attached separately by `_attach_run_log` once
    `paths.set_run_id(...)` resolves the workspace path.
    """
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    level = logging.DEBUG if verbose else logging.INFO
    root = logging.getLogger()
    root.setLevel(level)
    for h in list(root.handlers):
        root.removeHandler(h)
    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(logging.Formatter(
        "%(asctime)s %(name)s [%(levelname)s] %(message)s", "%H:%M:%S"
    ))
    root.addHandler(ch)
    # Global tape — every run appends here. Rotating to cap disk use.
    fh = RotatingFileHandler(
        LOGS_DIR / "orchestrator.log", maxBytes=5 * 1024 * 1024, backupCount=3,
        encoding="utf-8",
    )
    fh.setFormatter(_LOG_FORMATTER)
    root.addHandler(fh)


def _attach_run_log() -> Path:
    """Phase-2 logging: per-run FileHandler at workspace/<run_id>/orchestrator.log.

    Must be called after `paths.set_run_id(...)`. Returns the log file path.
    """
    paths.workspace.mkdir(parents=True, exist_ok=True)
    log_path = paths.workspace / "orchestrator.log"
    fh = logging.FileHandler(log_path, encoding="utf-8")
    fh.setFormatter(_LOG_FORMATTER)
    logging.getLogger().addHandler(fh)
    return log_path


def _write_resolved_config(cfg: Dict[str, Any]) -> Path:
    """Snapshot the effective run config into workspace/<run_id>/config.yaml.

    Captures the dict AFTER defaults + YAML + CLI have been merged, so the
    file alone is enough to reproduce the run (regardless of whether the
    user passed a config file, plain CLI args, or both).
    """
    paths.workspace.mkdir(parents=True, exist_ok=True)
    cfg_path = paths.workspace / "config.yaml"
    with cfg_path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
    return cfg_path


# ---------------------------------------------------------------------------
# Id allocation
# ---------------------------------------------------------------------------

def _next_id(existing: List[str]) -> str:
    """Return the next integer id as a string. Tolerates v5 ids of the form
    `<int>_<hash>` — splits on `_` and takes the integer prefix."""
    nums: List[int] = []
    for id in existing:
        head = id.split("_", 1)[0]
        try:
            nums.append(int(head))
        except ValueError:
            continue
    return str(max(nums, default=-1) + 1)


# ---------------------------------------------------------------------------
# Content hashing — fingerprint of the harness code that gets evaluated.
# Hash computed AFTER any propose_with_fix retries settle so it reflects the
# code that actually runs in evaluate_harness.
# ---------------------------------------------------------------------------

def _compute_content_hash(harness_dir: Path) -> str:
    """Return sha256(harness.py + sorted helper .py + requirements.txt)[:16].

    Excludes meta.json (avoids self-reference loop), PROPOSAL_READY (sentinel),
    and any per-dataset / sanity / runs subdirectories (eval artifacts).
    """
    harness_py = harness_dir / "harness.py"
    if not harness_py.exists():
        raise FileNotFoundError(f"harness.py missing in {harness_dir}")
    parts = [harness_py.read_bytes()]
    for p in sorted(harness_dir.glob("*.py")):
        if p.name == "harness.py":
            continue
        parts.append(p.read_bytes())
    req = harness_dir / "requirements.txt"
    if req.exists():
        parts.append(req.read_bytes())
    return hashlib.sha256(b"\n".join(parts)).hexdigest()[:16]


def _finalize_harness_id(int_id: str, harness_dir: Path) -> Tuple[str, Path]:
    """Rename `harnesses/<int>` → `harnesses/<int>_<hash8>` and stamp meta.json.

    Idempotent for already-finalized dirs (e.g. seed copied from `seeds/`
    that may already include a content_hash). Returns `(final_id, new_dir)`.
    """
    # Already finalized? (e.g. user passed a pre-named dir; or seed already had hash)
    if "_" in harness_dir.name:
        return harness_dir.name, harness_dir

    full_hash = _compute_content_hash(harness_dir)
    short = full_hash[:8]
    final_id = f"{int_id}_{short}"
    final_dir = harness_dir.parent / final_id
    if final_dir.exists() and final_dir != harness_dir:
        # Two harnesses with the same int prefix shouldn't exist; if they do,
        # someone manually fiddled the workspace. Don't clobber.
        raise RuntimeError(
            f"target dir already exists: {final_dir} (refusing to overwrite)"
        )
    if final_dir != harness_dir:
        os.rename(harness_dir, final_dir)

    # Stamp meta.json with content_hash + created_at (preserve CC's parent_ids
    # and description; don't overwrite an existing content_hash if it matches).
    meta_path = final_dir / "meta.json"
    meta: Dict[str, Any] = {}
    if meta_path.exists():
        try:
            with meta_path.open("r", encoding="utf-8") as f:
                meta = json.load(f)
        except Exception as exc:
            log.warning(f"could not parse {meta_path}: {exc} (overwriting)")
            meta = {}
    meta.setdefault("parent_ids", [])
    meta.setdefault("description", "")
    meta["content_hash"] = full_hash
    meta.setdefault("created_at", _dt.datetime.now().isoformat(timespec="seconds"))
    with meta_path.open("w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)

    return final_id, final_dir


# ---------------------------------------------------------------------------
# Seed harness bootstrap.
# When cfg.seed.enabled, copy seeds/<source>/ → <run>/harnesses/0/ at startup.
# ---------------------------------------------------------------------------

def _bootstrap_seed(seed_source: str) -> Optional[str]:
    """Copy the seed library entry into this run's harnesses/0/.

    Returns the destination integer-id string (always "0") if a copy happened
    or the dir already existed; returns None if no seed library entry was
    found at `seeds/<seed_source>/` (caller should treat as "no seed").
    """
    src = SEEDS_DIR / seed_source
    if not src.exists():
        log.error(
            f"seed source not found: {src}. Run with --no-seed or pick a "
            f"valid --seed-source from {[p.name for p in SEEDS_DIR.iterdir()] if SEEDS_DIR.exists() else '[]'}"
        )
        return None
    dst = paths.harnesses_dir / "0"
    if dst.exists():
        log.info(f"seed already present at {dst}; skipping copy")
        return "0"
    paths.harnesses_dir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dst)
    log.info(f"seed bootstrapped: {src} → {dst}")
    return "0"


# ---------------------------------------------------------------------------
# Per-dataset output helpers.
# Eval artifacts land at workspace/harnesses/<id>/<dataset>/...
# Sanity artifacts land at workspace/harnesses/<id>/<dataset>/sanity/...
# ---------------------------------------------------------------------------

def _dataset_dir(harness_dir: Path, dataset: str) -> Path:
    return harness_dir / dataset


def _sanity_dir(harness_dir: Path, dataset: str) -> Path:
    return harness_dir / dataset / "sanity"


def _read_dataset_metrics(harness_dir: Path, dataset: str) -> Dict[str, Any]:
    """Read score.json + token_usage.json for one dataset, return a metrics dict.

    Keys:
      raw_score:        float, benchmark_overall_eval_score (native scale)
      score_max:        int, judge's max score (10 for DynamicMem, 1 for LoCoMo/LongMemEval)
      per_user_stddev:  Optional[float], population stddev of per_user[*].reward;
                        None when fewer than 2 valid users (stddev undefined)
      tokens:           int, sum of total_tokens across all models in token_usage.json

    Defaults are chosen to make a missing/unreadable file behave like a 0-score
    completed eval (raw_score=0, score_max=10 for back-compat, no stddev, 0 tokens).
    """
    metrics: Dict[str, Any] = {
        "raw_score": 0.0,
        "score_max": 10,
        "per_user_stddev": None,
        "tokens": 0,
    }
    ds_dir = _dataset_dir(harness_dir, dataset)

    # score.json: raw_score + score_max + per_user_stddev
    score_json = ds_dir / "score.json"
    if score_json.exists():
        try:
            with score_json.open("r", encoding="utf-8") as f:
                data = json.load(f)
            bes = data.get("benchmark_eval_score", {})
            metrics["raw_score"] = float(bes.get("benchmark_overall_eval_score", 0.0))
            metrics["score_max"] = int(bes.get("score_max", 10))
            rewards = [
                float(v["reward"])
                for v in data.get("per_user", {}).values()
                if v.get("reward") is not None
            ]
            if len(rewards) >= 2:
                # Population stddev (ddof=0) — variance across the evaluated users.
                mean = sum(rewards) / len(rewards)
                metrics["per_user_stddev"] = (
                    sum((r - mean) ** 2 for r in rewards) / len(rewards)
                ) ** 0.5
        except Exception as exc:
            log.warning(f"could not parse {dataset} score.json for {harness_dir.name}: {exc}")

    # token_usage.json: sum total_tokens across all models
    tokens_json = ds_dir / "token_usage.json"
    if tokens_json.exists():
        try:
            with tokens_json.open("r", encoding="utf-8") as f:
                data = json.load(f)
            metrics["tokens"] = sum(
                int(model_usage.get("total_tokens", 0))
                for model_usage in data.values()
                if isinstance(model_usage, dict)
            )
        except Exception as exc:
            log.warning(f"could not parse {dataset} token_usage.json for {harness_dir.name}: {exc}")

    return metrics


def _write_failure(out_dir: Path, msg: str) -> None:
    """Write a stub score.json indicating orchestrator-level failure."""
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "benchmark_eval_score": {
            "benchmark_overall_eval_score": 0.0,
            "benchmark_overall_eval_standard_deviation": 0.0,
        },
        "per_user": {},
        "invalid_users": [{"user_id": "orchestrator", "error": msg}],
    }
    with (out_dir / "score.json").open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)


def _publish_run_artifacts(run_dir: Path, dst_dir: Path) -> None:
    """Move evaluator outputs from the transient runs/ staging dir into the
    per-dataset target dir, then remove the staging dir.

    Why move (not copy): runs/ exists only because the container needs a
    writable /out separate from the read-only /harness bind. After the host
    has the artifacts, leaving them in runs/ doubles disk use and adds
    visual clutter. We `shutil.copy2 + rmtree` so the dst_dir always lands
    on the same filesystem regardless of where runs/ was bound.

    Includes `subprocess.log` (container-side Phase 1/2 progress) so users
    don't have to dig into runs/<...>/ to inspect what happened inside the
    container.
    """
    dst_dir.mkdir(parents=True, exist_ok=True)
    for name in ("score.json", "token_usage.json", "subprocess.log"):
        src = run_dir / name
        if src.exists():
            shutil.copy2(str(src), str(dst_dir / name))
    for sub in ("traces", "memory_dumps"):
        src_dir = run_dir / sub
        if not src_dir.exists():
            continue
        dst_sub = dst_dir / sub
        dst_sub.mkdir(exist_ok=True)
        for p in src_dir.iterdir():
            shutil.copy2(str(p), str(dst_sub / p.name))
    # Drop the staging dir entirely. If a copy above failed, rmtree still
    # runs — the score.json that ends up in dst_dir remains the source of
    # truth, and duplicating staging on a partial failure isn't useful.
    shutil.rmtree(run_dir, ignore_errors=True)
    # Also rmdir the parent `runs/` if it's empty — keeps the workspace
    # listing clean when no eval is currently in flight. Silently a no-op
    # if a concurrent eval is using a sibling subdir.
    try:
        run_dir.parent.rmdir()
    except OSError:
        pass


def _build_objectives(
    per_dataset_metrics: Dict[str, Dict[str, Any]],
    harness_dir: Path,
) -> Dict[str, Any]:
    """Aggregate per-dataset metrics + harness-level attrs into a frontier objectives dict.

    Per-benchmark fields (one set per dataset, native scale preserved):
      - `accuracy_<dataset>`     raw judge score (DynamicMem 0-10, LoCoMo/LongMemEval 0-1)
      - `score_max_<dataset>`    judge's max — so consumers can normalize themselves
      - `robustness_<dataset>`   stddev of per-user reward (lower = more reliable);
                                 omitted when fewer than 2 valid users (stddev undefined)

    Harness-level fields (single value):
      - `accuracy`               mean of (raw / score_max) across datasets ∈ [0, 1].
                                 Equal weight per benchmark regardless of judge scale.
      - `code_length`            bytes of harness.py (rough simplicity proxy; lower = simpler)
      - `tokens_total`           sum of total_tokens across all datasets and models
                                 (rough $-cost proxy; lower = cheaper)

    These extra fields are **telemetry only** — `Frontier.OBJECTIVES` is still
    `("accuracy",)`, so selection algorithms ignore them. They surface to the
    proposer agent (which reads frontier.json directly) so CC can factor in
    "same accuracy, prefer simpler / cheaper / more reliable" when picking priors.
    """
    out: Dict[str, Any] = {}
    if not per_dataset_metrics:
        out["accuracy"] = 0.0
    else:
        normalized: List[float] = []
        total_tokens = 0
        for ds, m in per_dataset_metrics.items():
            raw = float(m.get("raw_score", 0.0))
            score_max = int(m.get("score_max", 10))
            out[f"accuracy_{ds}"] = raw
            out[f"score_max_{ds}"] = float(score_max)
            stddev = m.get("per_user_stddev")
            if stddev is not None:
                out[f"robustness_{ds}"] = float(stddev)
            normalized.append(raw / score_max if score_max > 0 else 0.0)
            total_tokens += int(m.get("tokens", 0))
        out["accuracy"] = sum(normalized) / len(normalized)  # ∈ [0, 1]
        out["tokens_total"] = total_tokens

    # Harness-level: code_length (best-effort; missing harness.py from a crashed
    # propose just means we record 0 rather than crashing).
    try:
        out["code_length"] = (harness_dir / "harness.py").stat().st_size
    except OSError:
        out["code_length"] = 0

    return out


# ---------------------------------------------------------------------------
# Sanity check — small real-data run per dataset, ensures harness runs without crashing
# ---------------------------------------------------------------------------

def _collect_sanity_errors(
    harness_dir: Path, datasets_config: Dict[str, Dict[str, Any]]
) -> Tuple[bool, str]:
    """Inspect sanity score.json for each dataset. Return (passed, error_trace).

    Harness fails sanity if ANY dataset has invalid_users non-empty OR any
    per_user entry has non-empty failure_info.
    """
    errors: List[str] = []
    for ds in datasets_config:
        score_path = _sanity_dir(harness_dir, ds) / "score.json"
        if not score_path.exists():
            errors.append(f"[{ds}] sanity score.json missing (singularity likely didn't launch)")
            continue
        try:
            with score_path.open("r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception as exc:
            errors.append(f"[{ds}] failed to parse sanity score.json: {exc}")
            continue
        invalid = data.get("invalid_users", [])
        for iu in invalid:
            errors.append(f"[{ds}] invalid user {iu.get('user_id', '?')}: {iu.get('error', '')}")
        for uid, v in data.get("per_user", {}).items():
            fi = v.get("failure_info")
            if fi:
                errors.append(f"[{ds}] user {uid} partial failure: {fi}")
    if not errors:
        return True, ""
    return False, "\n".join(errors)


async def sanity_check_harness(
    harness_id: str,
    image_path: Path,
    *,
    datasets_config: Dict[str, Dict[str, Any]],
    status: str,
    model: str,
    judge_model: str,
    update_type: str,
    max_sample_concurrent: int,
    gpu: bool = False,
) -> Tuple[bool, str]:
    """Run a small mode=check evaluation on every dataset. Never dumps memory.

    Returns (passed, error_trace). Artifacts go to `<harness>/<dataset>/sanity/`.
    """
    harness_dir = paths.harnesses_dir / harness_id

    for ds, params in datasets_config.items():
        sanity_dst = _sanity_dir(harness_dir, ds)
        run_dir = paths.runs_dir / f"{harness_id}_{int(time.time())}_{ds}_sanity"
        crashed: Optional[Exception] = None
        try:
            await run_evaluation(
                harness_dir=harness_dir,
                image_path=image_path,
                out_dir=run_dir,
                dataset=ds,
                status=status,
                mode="check",
                eval_n_samples=params["eval_n_samples"],  # unused at mode=check but required
                eval_n_qa=params["eval_n_qa"],
                check_n_samples=params["check_n_samples"],
                check_n_qa=params["check_n_qa"],
                model=model,
                judge_model=judge_model,
                update_type=update_type,
                max_sample_concurrent=max_sample_concurrent,
                memory_dumps="none",   # sanity never dumps
                gpu=gpu,
            )
        except Exception as exc:
            log.error(f"sanity crashed for {harness_id} [{ds}]: {exc}")
            crashed = exc
        # Always publish + cleanup, even on crash — the container may have
        # written subprocess.log / partial score.json that's useful for retry.
        _publish_run_artifacts(run_dir, sanity_dst)
        if not (sanity_dst / "score.json").exists():
            _write_failure(sanity_dst, f"sanity_crashed: {crashed}" if crashed else "no score.json produced")

    return _collect_sanity_errors(harness_dir, datasets_config)


# ---------------------------------------------------------------------------
# Full eval — one harness across every dataset (serial).
# ---------------------------------------------------------------------------

async def evaluate_harness(
    harness_id: str,
    image_path: Path,
    *,
    datasets_config: Dict[str, Dict[str, Any]],
    status: str,                  # search | test | devtest
    model: str,
    judge_model: str,
    update_type: str,
    max_sample_concurrent: int,
    memory_dumps: str,
    gpu: bool = False,
) -> Dict[str, Dict[str, Any]]:
    """Run the harness on every dataset (serial). Returns per-dataset metrics
    dicts (raw_score, score_max, per_user_stddev, tokens) — see
    `_read_dataset_metrics`. Consumed by `_build_objectives` which normalizes
    raw_score by score_max before mean and surfaces telemetry axes.

    `status` is the user-facing 3-value enum. Translation to the container's
    (mode, status) wire format:
      search   → (mode=eval,  container_status=search)
      test     → (mode=eval,  container_status=test)
      devtest  → (mode=check, container_status=search)   # search-split + small size
    """
    if status == "devtest":
        container_mode, container_status = "check", "search"
    else:
        container_mode, container_status = "eval", status

    harness_dir = paths.harnesses_dir / harness_id

    scores: Dict[str, Dict[str, Any]] = {}
    for ds, params in datasets_config.items():
        eval_ns = int(params.get("eval_n_samples", 1))
        eval_nq = params.get("eval_n_qa")
        check_ns = int(params.get("check_n_samples", 1))
        check_nq = int(params.get("check_n_qa", 3))
        run_dir = paths.runs_dir / f"{harness_id}_{int(time.time())}_{ds}"
        crashed: Optional[Exception] = None
        try:
            await run_evaluation(
                harness_dir=harness_dir,
                image_path=image_path,
                out_dir=run_dir,
                dataset=ds,
                status=container_status,
                mode=container_mode,
                eval_n_samples=eval_ns,
                eval_n_qa=eval_nq,
                check_n_samples=check_ns,
                check_n_qa=check_nq,
                model=model,
                judge_model=judge_model,
                update_type=update_type,
                max_sample_concurrent=max_sample_concurrent,
                memory_dumps=memory_dumps,
                gpu=gpu,
            )
        except Exception as exc:
            log.error(f"evaluation crashed for {harness_id} [{ds}]: {exc}")
            crashed = exc
        # Always publish + cleanup. If the container died mid-write,
        # subprocess.log + any partial score.json are still useful for triage.
        dst = _dataset_dir(harness_dir, ds)
        _publish_run_artifacts(run_dir, dst)
        if not (dst / "score.json").exists():
            _write_failure(dst, f"eval_crashed: {crashed}" if crashed else "no score.json produced")
        scores[ds] = _read_dataset_metrics(harness_dir, ds)

    return scores


# ---------------------------------------------------------------------------
# One harness from propose through eval (or sanity-skip). Returns
# (per_dataset_scores, sanity_status).
# ---------------------------------------------------------------------------

async def propose_eval_one(
    cfg: Dict[str, Any],
    new_id: str,
    *,
    is_seed: bool = False,
) -> Tuple[str, Dict[str, float], str, List[str]]:
    """End-to-end for one harness (seed or proposed).

    Returns (final_id, per_dataset_scores, sanity_status, parent_ids):
      - final_id: harness id after content-hash rename (e.g. "3_a1b2c3d4");
        falls back to the integer id if no harness.py was produced
        (proposer-failure path).
      - sanity_status: "passed" / "failed" / "skipped" / "passed_on_retry_N"
        (also "proposer_failed" / "env_build_failed").
      - parent_ids: list of harness ids the proposer drew from
        (empty for the seed; populated from `meta.json::parent_ids`).

    The harness directory is renamed `harnesses/<int>` →
    `harnesses/<int>_<hash8>` after the sanity-retry loop settles, so the
    suffix reflects the code that's actually evaluated.
    """
    datasets_config = cfg["datasets"]
    dataset_names = list(datasets_config.keys())
    status = cfg["status"]   # search | test | devtest

    # Sanity is skipped entirely when status=devtest (devtest IS a sanity-size
    # quick check by definition; running another sanity layer is redundant).
    # For search/test, sanity respects cfg["sanity"]["enabled"].
    sanity_enabled = (status != "devtest") and cfg["sanity"]["enabled"]

    harness_dir = paths.harnesses_dir / new_id
    final_id = new_id  # may get renamed to f"{new_id}_{hash8}" below

    def _settle_path() -> None:
        """Rename harness_dir → <int>_<hash8>. Updates outer-scope vars."""
        nonlocal harness_dir, final_id
        if (harness_dir / "harness.py").exists() and "_" not in harness_dir.name:
            final_id, harness_dir = _finalize_harness_id(new_id, harness_dir)

    # Propose (unless seed). No parent_id passed — CC browses the workspace
    # itself and records its chosen prior(s) in meta.json::parent_ids.
    if not is_seed:
        try:
            await propose(
                new_id=new_id,
                model=cfg["proposer"]["model"],
                max_turns=cfg["proposer"]["max_turns"],
                timeout_s=cfg["proposer"]["timeout_s"],
                disallowed_tools=cfg["proposer"]["disallowed_tools"],
                sanity_enabled=sanity_enabled,
            )
        except (TimeoutError, RuntimeError) as exc:
            log.error(f"proposer failed: {exc}")
            # Propose may have written nothing — finalize is a no-op then.
            _settle_path()
            return final_id, {ds: {"raw_score": 0.0, "score_max": 1, "per_user_stddev": None, "tokens": 0} for ds in dataset_names}, "proposer_failed", []

    # Build (or look up cached) env image. We do NOT host-side-validate the
    # harness anymore — that used to live in `forge.contract.validate` but
    # required host venv to mirror the container's package list (issue #6).
    # Now: validation happens naturally inside the container at sanity time
    # (or at evaluate time in mode=check) via launch.py::_load_harness_class.
    try:
        image_path = await ensure_image(harness_dir)
    except EnvBuildError as exc:
        log.error(f"env build failed for {new_id}: {exc}")
        _settle_path()
        for ds in dataset_names:
            _write_failure(_dataset_dir(harness_dir, ds), f"env_build_failed: {exc}")
        return final_id, {ds: {"raw_score": 0.0, "score_max": 1, "per_user_stddev": None, "tokens": 0} for ds in dataset_names}, "env_build_failed", _read_parent_ids(harness_dir)

    # Sanity retry loop (only when sanity_enabled + not seed — we trust the
    # seed harness to be clean; running sanity on it just wastes time.). All
    # operations here use the integer-only path; rename happens after the
    # loop settles.
    sanity_status = "skipped"
    if sanity_enabled and not is_seed:
        max_retries = int(cfg["sanity"]["max_retries"])
        for attempt in range(max_retries + 1):
            passed, error_trace = await sanity_check_harness(
                new_id, image_path,
                datasets_config=datasets_config,
                status=cfg["status"],
                model=cfg["model"], judge_model=cfg["judge_model"],
                update_type=cfg["update_type"],
                max_sample_concurrent=cfg["max_sample_concurrent"],
                gpu=cfg["gpu"]["enabled"],
            )
            if passed:
                sanity_status = "passed" if attempt == 0 else f"passed_on_retry_{attempt}"
                log.info(f"sanity OK for {new_id} (attempt {attempt}/{max_retries})")
                break
            log.warning(
                f"sanity FAILED for {new_id} (attempt {attempt}/{max_retries}):\n{error_trace}"
            )
            if attempt >= max_retries:
                sanity_status = "failed"
                break
            # Retry: ask CC to fix its own harness based on the error trace
            try:
                await propose_with_fix(
                    new_id=new_id,
                    error_trace=error_trace,
                    model=cfg["proposer"]["model"],
                    max_turns=cfg["proposer"]["max_turns"],
                    timeout_s=cfg["proposer"]["timeout_s"],
                    disallowed_tools=cfg["proposer"]["disallowed_tools"],
                    sanity_enabled=sanity_enabled,
                )
            except (TimeoutError, RuntimeError) as exc:
                log.error(f"propose_with_fix failed for {new_id}: {exc}")
                sanity_status = "failed"
                break
            # CC may have edited requirements.txt during the fix → re-resolve
            # the container image (cached unless requirements.txt actually
            # changed).
            try:
                image_path = await ensure_image(harness_dir)
            except EnvBuildError as exc:
                log.error(f"env rebuild after fix failed for {new_id}: {exc}")
                sanity_status = "failed"
                break

        if sanity_status == "failed":
            log.error(f"sanity_failed for {new_id}; skipping full eval")
            _settle_path()
            for ds in dataset_names:
                _write_failure(
                    _dataset_dir(harness_dir, ds),
                    "sanity_failed_after_retries",
                )
            return final_id, {ds: {"raw_score": 0.0, "score_max": 1, "per_user_stddev": None, "tokens": 0} for ds in dataset_names}, "failed", _read_parent_ids(harness_dir)

    # Sanity loop settled (or skipped). Compute hash on the post-fix code,
    # rename `<int>` → `<int>_<hash8>`, then run full eval against the new dir.
    _settle_path()

    per_ds = await evaluate_harness(
        final_id, image_path,
        datasets_config=datasets_config,
        status=status,
        model=cfg["model"], judge_model=cfg["judge_model"],
        update_type=cfg["update_type"],
        max_sample_concurrent=cfg["max_sample_concurrent"],
        memory_dumps=cfg["memory_dumps"],
        gpu=cfg["gpu"]["enabled"],
    )
    return final_id, per_ds, sanity_status, _read_parent_ids(harness_dir)


# ---------------------------------------------------------------------------
# Outer loop
# ---------------------------------------------------------------------------

async def search_loop(cfg: Dict[str, Any]) -> None:
    ensure_dirs()
    frontier = Frontier.load(paths.frontier_path)

    datasets_config: Dict[str, Dict[str, Any]] = cfg["datasets"]
    dataset_names = list(datasets_config.keys())

    # Seed harness bootstrap (v5): copy seeds/<source>/ → harnesses/0/ when
    # enabled. Then evaluate seed and rename → 0_<hash>. Skips the seed entirely
    # when seed.enabled=false, so CC's first proposal becomes the first entry.
    seed_already_in_frontier = any(e.id.split("_", 1)[0] == "0" for e in frontier.all_entries())
    if cfg["seed"]["enabled"] and not seed_already_in_frontier:
        seed_int_id = _bootstrap_seed(cfg["seed"]["source"])
        if seed_int_id is None:
            log.error("seed bootstrap failed; aborting search")
            return
        log.info(f"evaluating seed harness on {dataset_names} ...")
        seed_final_id, per_ds, sanity_status, parent_ids = await propose_eval_one(
            cfg, new_id=seed_int_id, is_seed=True,
        )
        seed_dir = paths.harnesses_dir / seed_final_id
        objectives = _build_objectives(per_ds, seed_dir)
        seed_meta = _read_meta(seed_dir)
        entry = Entry(
            id=seed_final_id, objectives=objectives, parent_ids=parent_ids,
            content_hash=seed_meta.get("content_hash"),
            created_at=seed_meta.get("created_at"),
        )
        frontier.add(entry)
        _persist_sanity_status(entry.id, sanity_status)
        frontier.save(paths.frontier_path)
        log.info(
            f"seed {seed_final_id}: mean={objectives['accuracy']:.3f} "
            + ", ".join(
                f"{ds}={per_ds.get(ds, {}).get('raw_score', 0):.3f}"
                for ds in dataset_names
            )
            + f"  [sanity={sanity_status}]"
        )
    elif not cfg["seed"]["enabled"] and not seed_already_in_frontier:
        log.info("seed disabled — first proposed harness will have no prior to reference")

    # Search loop. v4: no parent selection — for each step, propose k harnesses
    # back-to-back; each call lets CC browse the workspace and pick its own
    # priors. v5: dir is renamed to <int>_<hash> after sanity settles.
    k = int(cfg["propose"]["k_per_step"])
    for step in range(cfg["steps"]):
        log.info(f"[step {step+1}/{cfg['steps']}] proposing {k} harness(es)")
        for j in range(k):
            int_id = _next_id([e.id for e in frontier.all_entries()])
            log.info(f"[step {step+1}/{cfg['steps']}] candidate {j+1}/{k} → int_id={int_id}")
            final_id, per_ds, sanity_status, parent_ids = await propose_eval_one(
                cfg, new_id=int_id, is_seed=False,
            )
            new_dir = paths.harnesses_dir / final_id
            objectives = _build_objectives(per_ds, new_dir)
            new_meta = _read_meta(new_dir)
            entry = Entry(
                id=final_id, objectives=objectives, parent_ids=parent_ids,
                content_hash=new_meta.get("content_hash"),
                created_at=new_meta.get("created_at"),
            )
            frontier.add(entry)
            _persist_sanity_status(entry.id, sanity_status)
            frontier.save(paths.frontier_path)
            log.info(
                f"[step {step+1}/{j+1}] {final_id} mean={objectives['accuracy']:.3f} "
                + ", ".join(
                    f"{ds}={per_ds.get(ds, {}).get('raw_score', 0):.3f}"
                    for ds in dataset_names
                )
                + f"  [sanity={sanity_status}]  parent_ids={parent_ids}"
            )


# ---------------------------------------------------------------------------
# sanity_status is orthogonal to selection; we keep it as a sidecar file
# so we don't have to plumb it through the Frontier dataclass yet.
# ---------------------------------------------------------------------------

def _persist_sanity_status(harness_id: str, status: str) -> None:
    ds_dir = paths.harnesses_dir / harness_id
    ds_dir.mkdir(parents=True, exist_ok=True)
    try:
        with (ds_dir / "sanity_status.txt").open("w", encoding="utf-8") as f:
            f.write(status + "\n")
    except OSError as exc:
        log.warning(f"could not write sanity_status for {harness_id}: {exc}")


def _read_meta(harness_dir: Path) -> Dict[str, Any]:
    """Read meta.json (returns {} if missing/invalid)."""
    meta_path = harness_dir / "meta.json"
    if not meta_path.exists():
        return {}
    try:
        with meta_path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:
        log.warning(f"could not parse meta.json for {harness_dir.name}: {exc}")
        return {}


def _read_parent_ids(harness_dir: Path) -> List[str]:
    """Read `meta.json::parent_ids` (or fall back to old `parent_id`).

    Returns:
        List of harness ids that the proposer says it drew from. Empty list
        if meta.json is missing or doesn't list any (e.g. seed harness).
    """
    meta = _read_meta(harness_dir)
    if not meta:
        return []
    raw = meta.get("parent_ids")
    if raw is None:
        # Legacy single-parent schema
        legacy = meta.get("parent_id")
        if legacy is None or legacy == "":
            return []
        return [str(legacy)]
    if isinstance(raw, str):
        return [raw] if raw else []
    if isinstance(raw, list):
        return [str(x) for x in raw if x]
    log.warning(
        f"meta.json::parent_ids in {harness_dir.name} has unexpected type "
        f"{type(raw).__name__}; ignoring"
    )
    return []


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    # allow_abbrev=False: avoid surprising prefix matching. Without this,
    # `--mode check` would be parsed as `--model check` (since "mode" is a
    # prefix of "model"), silently using "check" as the OpenAI model name
    # rather than erroring as "unrecognized argument".
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument(
        "--config",
        default=None,
        help="Path to a YAML config file. CLI flags override its values.",
    )
    # Each override defaults to None so we can detect "explicitly set" vs "use config/default"
    parser.add_argument("--steps", type=int, default=None)
    parser.add_argument(
        "--datasets", default=None,
        help="Comma-separated dataset names. If given, replaces any YAML "
             "`datasets:` block and applies global eval_n_*/check_n_* uniformly.",
    )
    parser.add_argument(
        "--status",
        default=None,
        choices=["search", "test", "devtest"],
        help="search = training/exploration on search split; "
             "test = held-out evaluation on test split; "
             "devtest = quick dev verification (search split + check sizes + skip sanity).",
    )

    parser.add_argument("--eval-n-samples", type=int, default=None,
                        help="Full-eval task-list cap (overrides every dataset's eval_n_samples)")
    parser.add_argument("--eval-n-qa", type=int, default=None,
                        help="Full-eval per-sample QA cap (ignored for longmemeval)")
    parser.add_argument("--check-n-samples", type=int, default=None,
                        help="Sanity-check task-list cap (default 1)")
    parser.add_argument("--check-n-qa", type=int, default=None,
                        help="Sanity-check per-sample QA cap (default 3, ignored for longmemeval)")

    parser.add_argument("--model", default=None)
    parser.add_argument("--judge-model", default=None)
    parser.add_argument("--update-type", default=None,
                        choices=["all_at_once", "chunked", "sequential"])
    parser.add_argument("--max-sample-concurrent", type=int, default=None)
    parser.add_argument("--memory-dumps", default=None, choices=["full", "stats", "none"],
                        help="Post-Phase-1 memo dump policy: full / stats / none")

    parser.add_argument("--proposer-model", default=None)
    parser.add_argument("--proposer-max-turns", type=int, default=None)
    parser.add_argument("--proposer-timeout-s", type=int, default=None)
    parser.add_argument(
        "--proposer-disallowed-tools", default=None,
        help='Comma-separated list of tools the proposer cannot use (default ["mcp__*"]). '
             'Pass "" to allow all tools. Examples: "mcp__*", "Bash,WebFetch,mcp__*".',
    )

    parser.add_argument("--tau", type=float, default=None,
                        help="Softmax temperature for Frontier.sample_parent (held-out test only)")

    parser.add_argument("--k-per-step", type=int, default=None,
                        help="Harnesses proposed per outer-loop step (default 2)")

    parser.add_argument("--no-sanity", action="store_true",
                        help="Disable the pre-eval sanity-check stage (mode=eval only)")
    parser.add_argument("--sanity-max-retries", type=int, default=None,
                        help="Max propose_with_fix retries when sanity fails (default 2)")

    parser.add_argument("--run-name", default=None,
                        help="Per-run workspace dir under workspace/. "
                             "Defaults to a timestamp (YYYYMMDD_HHMMSS).")
    parser.add_argument("--no-seed", action="store_true",
                        help="Skip copying the seed harness — first proposed "
                             "harness has no prior to reference.")
    parser.add_argument("--seed-source", default=None,
                        help="Which subdir under seeds/ to copy as harness 0 "
                             "(default 'no_memory').")

    parser.add_argument("--gpu", action="store_true",
                        help="Pass --nv to evaluator's singularity exec so the "
                             "container can use the host's NVIDIA driver. "
                             "Default off (CPU-only).")

    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    _setup_logging(args.verbose)
    cfg = _resolve_config(args)
    paths.set_run_id(cfg["run_name"])
    run_log = _attach_run_log()
    cfg_snapshot = _write_resolved_config(cfg)
    log.info(
        f"run config: {json.dumps({k: v for k, v in cfg.items() if k != 'proposer'}, default=str)}"
    )
    log.info(f"workspace: {paths.workspace}")
    log.info(f"run log: {run_log}")
    log.info(f"config snapshot: {cfg_snapshot}")
    asyncio.run(search_loop(cfg))


if __name__ == "__main__":
    main()
